@startjson
{
	"playerNumbers": [
		{
			"direction": "N",
			"number": "-1",
			"name": "name"
		},
		{
			"direction": "S",
			"number": "",
			"name": "name"
		}
	],
	"section": 99,
	"table": 99,
	"round": 99
}
@endjson
