@startjson
{
	"user": {
		"CreatedAt": "2024-08-11T21:09:46.1765123+02:00",
		"UpdatedAt": "2024-08-11T21:09:46.1765123+02:00",
		"DeletedAt": null,
		"ID": 4,
		"role_id": 3,
		"username": "test2",
		"name": "",
		"surname": "",
		"email": "tesat@bmacharia.com",
		"pid": ""
	}
}
@endjson
