@startuml
State B as "befor login"{
    state B1 as "login"
    state B2 as "register"
 B1 -> B2
 B2 -> B1
}

B1 --> A1:guest is consider\n a login user
'State A as "after login"{
state A1 as "home"
state A3 as "code join"
state C as "settings"{
    state C1 as "profile"
    state C2 as "app"
}
[*]->C : from close to all point in app
state A4 as "input yourself"
      A4 :you add  table and position
      A4 : add name, cid, ect when you as a guest (for future)
C -> B1
 A3 --> A4
 A4 -->D
 A1 -> A3
 A3 ->A1
 D --> A1 : exit tournament
state D as "turnament"{
   state D0 as "summary"
   state D1 as "info recive"
   state D2 as "movment"
   state D3 as "input data"
   D0 --> D1
   D0 --> D2
   D0 --> D3
   D0 <-- D1
   D0 <-- D2
   D0 <-- D3
}
state E as "admin"{
    state E1 as "Edit input data"
    state E2 as "Edit user data"
}
A1 --> E :only for "admin"



@enduml
