name: generate plantuml
on:
  push:
    branches:
      - main
    paths:
      - 'diagrams/*.puml'
      - 'diagrams/*.pu'
      - 'diagrams/*.pml'
      - 'diagrams/*.plantuml'
  workflow_dispatch: 
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: plantuml
        id: plantuml
        uses: grassedge/generate-plantuml-action@master
        with:
          path: diagrams
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
